# Generated by Django 4.2.3 on 2023-09-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='main_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post_name',
        ),
    ]
